/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `bigtree_404s`;
CREATE TABLE `bigtree_404s` ( `id` int(11) NOT NULL auto_increment, `broken_url` varchar(255) NOT NULL default '', `redirect_url` varchar(255) NOT NULL default '', `requests` int(11) NOT NULL default '0', `requesters` text NOT NULL, `referers` text NOT NULL, `ignored` char(2) NOT NULL default '', PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_api_tokens`;
CREATE TABLE `bigtree_api_tokens` ( `id` int(11) NOT NULL auto_increment, `token` varchar(255) NOT NULL, `user` int(11) NOT NULL, `expires` datetime NOT NULL, `temporary` char(2) NOT NULL, `readonly` char(2) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_feeds`;
CREATE TABLE `bigtree_feeds` ( `id` int(11) NOT NULL auto_increment, `route` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `description` text NOT NULL, `type` varchar(255) NOT NULL, `table` varchar(255) NOT NULL, `fields` text NOT NULL, `options` text NOT NULL, `package` int(11) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_field_types`;
CREATE TABLE `bigtree_field_types` ( `id` varchar(255) NOT NULL default '', `foundry_id` int(11) NOT NULL, `author` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `primary_version` int(11) NOT NULL, `secondary_version` int(11) NOT NULL, `tertiary_version` int(11) NOT NULL, `description` text NOT NULL, `release_notes` text NOT NULL, `files` text NOT NULL, `pages` char(2) NOT NULL, `modules` char(2) NOT NULL, `sidelets` char(2) NOT NULL, `downloaded` char(2) NOT NULL, `private` char(2) NOT NULL, `last_updated` datetime NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_import_matching`;
CREATE TABLE `bigtree_import_matching` ( `id` int(11) NOT NULL auto_increment, `table` varchar(255) NOT NULL, `my_id` int(11) NOT NULL, `other_id` int(11) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `bigtree_locks`;
CREATE TABLE `bigtree_locks` ( `id` int(11) NOT NULL auto_increment, `table` varchar(255) NOT NULL, `item_id` varchar(255) NOT NULL, `last_accessed` timestamp NOT NULL default CURRENT_TIMESTAMP, `user` int(11) NOT NULL, `title` varchar(255) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_module_actions`;
CREATE TABLE `bigtree_module_actions` ( `id` int(11) NOT NULL auto_increment, `module` int(11) NOT NULL default '0', `name` varchar(255) NOT NULL default '', `route` varchar(255) NOT NULL default '', `in_nav` char(2) NOT NULL default '', `form` int(11) NOT NULL, `view` int(11) NOT NULL, `class` varchar(255) NOT NULL, `position` int(11) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_module_forms`;
CREATE TABLE `bigtree_module_forms` ( `id` int(11) NOT NULL auto_increment, `title` varchar(255) NOT NULL, `javascript` varchar(255) NOT NULL, `css` varchar(255) NOT NULL, `callback` varchar(255) NOT NULL, `table` varchar(255) NOT NULL, `fields` text NOT NULL, `positioning` text NOT NULL, `default_position` varchar(255) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_module_groups`;
CREATE TABLE `bigtree_module_groups` ( `id` int(11) NOT NULL auto_increment, `name` varchar(255) NOT NULL, `position` int(11) NOT NULL default '0', `package` int(11) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_module_packages`;
CREATE TABLE `bigtree_module_packages` ( `id` int(11) NOT NULL auto_increment, `foundry_id` int(11) NOT NULL, `author` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `primary_version` int(11) NOT NULL, `secondary_version` int(11) NOT NULL, `tertiary_version` int(11) NOT NULL, `description` text NOT NULL, `release_notes` text NOT NULL, `details` text NOT NULL, `group_id` int(11) NOT NULL, `module_id` int(11) NOT NULL, `tables` text NOT NULL, `files` text NOT NULL, `downloaded` char(2) NOT NULL, `private` char(2) NOT NULL, `last_updated` datetime NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_module_views`;
CREATE TABLE `bigtree_module_views` ( `id` int(11) NOT NULL auto_increment, `title` varchar(255) NOT NULL default '', `description` text NOT NULL, `type` varchar(255) NOT NULL default '', `table` varchar(255) NOT NULL default '', `fields` text NOT NULL, `options` text NOT NULL, `actions` text NOT NULL, `suffix` varchar(255) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_modules`;
CREATE TABLE `bigtree_modules` ( `id` int(11) NOT NULL auto_increment, `name` varchar(255) NOT NULL default '', `description` text NOT NULL, `image` varchar(255) NOT NULL default '', `route` varchar(255) NOT NULL default '', `class` varchar(255) NOT NULL default '', `group` int(11) NOT NULL default '0', `position` int(11) NOT NULL, `package` int(11) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_objects`;
CREATE TABLE `bigtree_objects` ( `id` int(11) NOT NULL auto_increment, `module` int(11) default NULL, `name` varchar(255) default NULL, `file` varchar(255) default NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_pages`;
CREATE TABLE `bigtree_pages` ( `id` int(11) NOT NULL auto_increment, `parent` int(11) NOT NULL default '0', `in_nav` varchar(5) character set latin1 NOT NULL default 'on', `nav_title` varchar(255) collate utf8_bin NOT NULL, `route` varchar(30) collate utf8_bin NOT NULL, `path` text collate utf8_bin NOT NULL, `title` varchar(255) collate utf8_bin NOT NULL, `meta_keywords` text collate utf8_bin NOT NULL, `meta_description` text collate utf8_bin NOT NULL, `template` varchar(255) collate utf8_bin NOT NULL, `external` varchar(255) collate utf8_bin NOT NULL, `new_window` varchar(5) character set latin1 NOT NULL default '', `resources` longtext collate utf8_bin NOT NULL, `sidebar` longtext collate utf8_bin NOT NULL, `archived` char(2) character set latin1 NOT NULL, `permissions` text character set latin1 NOT NULL, `notes` text collate utf8_bin NOT NULL, `locked` char(2) character set latin1 NOT NULL, `position` int(11) NOT NULL default '0', `created_at` datetime NOT NULL, `updated_at` timestamp NOT NULL default '0000-00-00 00:00:00' on update CURRENT_TIMESTAMP, `publish_at` date default NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
LOCK TABLES `bigtree_pages` WRITE;
/*!40000 ALTER TABLE `bigtree_pages` DISABLE KEYS */;
INSERT INTO `bigtree_pages` (`id`,`parent`,`in_nav`,`nav_title`,`route`,`path`,`title`,`meta_keywords`,`meta_description`,`template`,`external`,`new_window`,`resources`,`sidebar`,`archived`,`permissions`,`notes`,`locked`,`position`,`created_at`,`updated_at`,`publish_at`) VALUES (1,-1,'on','BigTree Site','',X'','BigTree Site',X'',X'','','','',X'',X'','','',X'','',0,'0000-00-00 00:00:00','2010-08-27 12:00:50',NULL);
/*!40000 ALTER TABLE `bigtree_pages` ENABLE KEYS */;
UNLOCK TABLES;
DROP TABLE IF EXISTS `bigtree_pending_changes`;
CREATE TABLE `bigtree_pending_changes` ( `id` int(11) NOT NULL auto_increment, `user` int(11) NOT NULL, `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP, `title` varchar(255) NOT NULL, `comments` longtext NOT NULL, `table` varchar(255) NOT NULL, `changes` longtext NOT NULL, `mtm_changes` longtext NOT NULL, `tags_changes` longtext NOT NULL, `resources_changes` longtext NOT NULL, `item_id` int(11) NOT NULL, `type` varchar(15) NOT NULL, `module` varchar(10) NOT NULL, `pending_page_parent` int(11) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_resources`;
CREATE TABLE `bigtree_resources` ( `id` int(11) NOT NULL auto_increment, `table` varchar(255) NOT NULL, `entry` int(11) NOT NULL, `file` varchar(255) NOT NULL, `title` varchar(255) NOT NULL, `description` text NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_route_history`;
CREATE TABLE `bigtree_route_history` ( `id` int(11) NOT NULL auto_increment, `old_route` varchar(255) NOT NULL, `new_route` varchar(255) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_settings`;
CREATE TABLE `bigtree_settings` ( `id` varchar(255) NOT NULL default '', `value` text NOT NULL, `type` varchar(255) NOT NULL, `title` varchar(255) NOT NULL, `description` text NOT NULL, `locked` char(2) NOT NULL, `module` int(11) NOT NULL, `package` int(11) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
LOCK TABLES `bigtree_settings` WRITE;
/*!40000 ALTER TABLE `bigtree_settings` DISABLE KEYS */;
INSERT INTO `bigtree_settings` (`id`,`value`,`type`,`title`,`description`,`locked`,`module`,`package`) VALUES ('content-due-date','','text','Content Due Date','','on',0,0), ('content-gathering','','checkbox','Allow Content Gathering','','on',0,0), ('ping-search-engines','','checkbox','Ping Search Engines','','',0,0), ('google-analytics-email','','text','Google Analytics Email Address','','',0,0), ('google-analytics-password','','text','Google Analytics Password','','',0,0), ('google-analytics-profile','','text','Google Analytics Profile ID','','',0,0);
/*!40000 ALTER TABLE `bigtree_settings` ENABLE KEYS */;
UNLOCK TABLES;
DROP TABLE IF EXISTS `bigtree_sidelets`;
CREATE TABLE `bigtree_sidelets` ( `id` varchar(255) NOT NULL, `title` varchar(255) NOT NULL, `description` text NOT NULL, `resources` text NOT NULL, `position` int(11) NOT NULL, `package` int(11) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_tags`;
CREATE TABLE `bigtree_tags` ( `id` int(11) NOT NULL auto_increment, `tag` varchar(255) NOT NULL, `metaphone` varchar(255) NOT NULL, `route` varchar(255) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_tags_rel`;
CREATE TABLE `bigtree_tags_rel` ( `id` int(11) NOT NULL auto_increment, `module` int(11) NOT NULL, `tag` int(11) NOT NULL, `entry` varchar(255) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_templates`;
CREATE TABLE `bigtree_templates` ( `id` varchar(255) NOT NULL default '', `name` varchar(255) NOT NULL default '', `image` varchar(255) NOT NULL default '', `module` varchar(255) NOT NULL default '', `resources` text NOT NULL, `position` int(11) NOT NULL default '0', `description` text NOT NULL, `level` int(11) NOT NULL, `package` int(11) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
LOCK TABLES `bigtree_templates` WRITE;
/*!40000 ALTER TABLE `bigtree_templates` DISABLE KEYS */;
INSERT INTO `bigtree_templates` (`id`,`name`,`image`,`module`,`resources`,`position`,`description`,`level`,`package`) VALUES ('content','Content','','','a:2:{i:0;a:3:{s:2:\"id\";s:11:\"page_header\";s:4:\"name\";s:11:\"Page Header\";s:4:\"type\";s:4:\"text\";}i:1;a:3:{s:2:\"id\";s:12:\"page_content\";s:4:\"name\";s:12:\"Page Content\";s:4:\"type\";s:4:\"html\";}}',2,'Normal template for content.',0,0);
/*!40000 ALTER TABLE `bigtree_templates` ENABLE KEYS */;
UNLOCK TABLES;
DROP TABLE IF EXISTS `bigtree_transactions`;
CREATE TABLE `bigtree_transactions` ( `id` int(11) NOT NULL auto_increment, `type` varchar(255) NOT NULL, `target` varchar(255) NOT NULL, `action` varchar(255) NOT NULL, `date` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `bigtree_user_favorites`;
CREATE TABLE `bigtree_user_favorites` ( `id` int(11) NOT NULL auto_increment, `user` int(11) NOT NULL, `title` varchar(255) NOT NULL, `url` varchar(255) NOT NULL, `count` int(11) NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
DROP TABLE IF EXISTS `bigtree_users`;
CREATE TABLE `bigtree_users` ( `id` int(11) NOT NULL auto_increment, `email` varchar(255) character set latin1 NOT NULL default '', `password` varchar(255) character set latin1 NOT NULL, `name` varchar(255) character set latin1 NOT NULL default '', `phone` varchar(255) character set latin1 NOT NULL default '', `company` varchar(255) character set latin1 NOT NULL default '', `level` int(11) NOT NULL default '0', `permissions` text character set latin1 NOT NULL, `change_password_hash` varchar(255) NOT NULL, `foundry_author` text NOT NULL, PRIMARY KEY  (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
